project:
  type: website

website:
  title: "Augmented tuto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tuto.ipynb
        text: Notebook

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true