name: encoder-tuto
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.4=h50f4ffc_0
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.4=h50f4ffc_0
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.19=ha0b305a_0
  - packaging=25.0=py311hca03da5_1
  - pip=26.0.1=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.10.2=py311hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - anyio==4.12.1
      - appnope==0.1.4
      - asttokens==3.0.1
      - attrs==25.4.0
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.5.0
      - debugpy==1.8.20
      - decorator==5.2.1
      - dill==0.4.0
      - executing==2.2.1
      - filelock==3.20.3
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.2
      - idna==3.11
      - ipykernel==7.2.0
      - ipython==9.10.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - multidict==6.7.1
      - multiprocess==0.70.18
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - numpy==2.4.2
      - pandas==3.0.0
      - parso==0.8.6
      - pexpect==4.9.0
      - pillow==12.1.1
      - platformdirs==4.5.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.2.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==23.0.0
      - pygments==2.19.2
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - regex==2026.1.15
      - requests==2.32.5
      - safetensors==0.7.0
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - tokenizers==0.21.4
      - torch==2.10.0
      - tornado==6.5.4
      - tqdm==4.67.3
      - traitlets==5.14.3
      - transformers==4.52.4
      - typing-extensions==4.15.0
      - urllib3==2.6.3
      - wcwidth==0.6.0
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /opt/miniconda3/envs/encoder-tuto
