name: VENV
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=3_kmp_llvm
  - attr=2.5.1=h166bdaf_1
  - babel=2.17.0=pyhd8ed1ab_0
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - commonmark=0.9.1=py_0
  - cpython=3.11.13=py311hd8ed1ab_0
  - css_inline=0.15.0=py311hdae7d1d_0
  - cuda-crt-tools=12.9.86=ha770c72_1
  - cuda-cudart=12.9.79=h5888daf_0
  - cuda-cudart_linux-64=12.9.79=h3f2d84a_0
  - cuda-cuobjdump=12.9.82=hbd13f7d_0
  - cuda-cupti=12.9.79=h9ab20c4_0
  - cuda-nvcc-tools=12.9.86=he02047a_1
  - cuda-nvdisasm=12.9.88=hbd13f7d_0
  - cuda-nvrtc=12.9.86=h5888daf_0
  - cuda-nvtx=12.9.79=h5888daf_0
  - cuda-nvvm-tools=12.9.86=he02047a_1
  - cuda-version=12.9=h4f385c5_3
  - cudnn=9.10.1.4=h7646684_0
  - faicons=0.2.2=pyhd8ed1ab_1
  - filelock=3.18.0=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py311h0f6cedb_0
  - great_tables=0.17.0=pyhd8ed1ab_0
  - htmltools=0.6.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - ld_impl_linux-64=2.43=h1423503_5
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libblas=3.9.0=31_hfdb39a5_mkl
  - libcap=2.75=h39aace5_0
  - libcblas=3.9.0=31_h372d94f_mkl
  - libcublas=12.9.1.4=h9ab20c4_0
  - libcudnn=9.10.1.4=h4840ae0_0
  - libcudnn-dev=9.10.1.4=hcd2ec93_0
  - libcudss=0.6.0.5=hcd2ec93_0
  - libcufft=11.4.1.4=h5888daf_0
  - libcufile=1.14.1.1=ha8da6e3_0
  - libcurand=10.3.10.19=h9ab20c4_0
  - libcusolver=11.7.5.82=h9ab20c4_0
  - libcusparse=12.5.10.65=h5888daf_0
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libgomp=15.1.0=h767d61c_2
  - libgpg-error=1.55=h3f2d84a_0
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - liblapack=3.9.0=31_hc41d3b0_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - libmagma=2.9.0=h19665d7_1
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjitlink=12.9.86=h5888daf_0
  - libprotobuf=5.29.3=h501fc15_1
  - libsqlite=3.50.1=hee588c1_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=15.1.0=h4852527_2
  - libsystemd0=257.6=h4e0b6ca_0
  - libtorch=2.7.1=cuda126_mkl_hc2b21a2_300
  - libudev1=257.6=hbe16f8c_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.51.0=hb9d3cd8_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=20.1.7=h024ca30_0
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.2=py311h2dc5d0c_1
  - mkl=2024.2.2=ha957f24_16
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - narwhals=1.43.1=pyhe01879c_0
  - nccl=2.27.3.1=h9b8ff78_0
  - ncurses=6.5=h2d0b736_3
  - networkx=3.5=pyhe01879c_0
  - numpy=2.3.0=py311h519dc76_0
  - openssl=3.5.0=h7b32b05_1
  - optree=0.16.0=py311hd18a35c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.0=py311h7db5c69_0
  - pip=25.1.1=pyh8b19718_0
  - plotly=6.1.2=pyhd8ed1ab_0
  - pybind11=2.13.6=pyhc790b64_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - python=3.11.13=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=7_cp311
  - pytorch=2.7.1=cuda126_mkl_py311_hcada2b2_300
  - pytz=2025.2=pyhd8ed1ab_0
  - rdma-core=57.0=h5888daf_0
  - readline=8.2=h8c095d6_2
  - scikit-learn=1.7.0=py311h57cc02b_1
  - scipy=1.15.2=py311h8f841c2_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sleef=3.8=h1b44611_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2021.13.0=hceb3a55_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - typing-extensions=4.14.0=h32cad80_0
  - typing_extensions=4.14.0=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - accelerate==1.8.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aiosignal==1.3.2
      - attrs==25.3.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==3.6.0
      - dill==0.3.8
      - einops==0.8.1
      - flash-attn==2.8.0.post2
      - fonttools==4.58.4
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - hf-xet==1.1.4
      - huggingface-hub==0.33.0
      - idna==3.10
      - kaleido==0.2.1
      - kiwisolver==1.4.8
      - matplotlib==3.10.3
      - mergedeep==1.3.4
      - multidict==6.5.0
      - multiprocess==0.70.16
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - pillow==11.2.1
      - propcache==0.3.2
      - psutil==7.0.0
      - pyarrow==20.0.0
      - pygad==3.4.0
      - pyparsing==3.2.3
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.4
      - safetensors==0.5.3
      - tokenizers==0.21.1
      - tqdm==4.67.1
      - transformers==4.52.4
      - triton==3.3.1
      - urllib3==2.5.0
      - xxhash==3.5.0
      - yarl==1.20.1
prefix: /home/onyxia/miniconda3/envs/VENV
